'use strict';

angular.module('myApp.pokemonList', ['ngRoute'])

    .config(['$routeProvider', function($routeProvider) {
        $routeProvider.when('/pokemonList', {
            templateUrl: 'pokemon/pokemonList.html',
            controller: 'PokemonListCtrl'
        });
    }])

    .controller('PokemonListCtrl', ['$scope', function($scope) {


        $scope.pokemonList = [
            {
                "VI": 88,
                "additional_cp_multiplier": 0.032608892768621445,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 2206,
                "id": 13257771392878105277,
                "individual_attack": 15,
                "individual_defense": 14,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 230,
                "move_2": 58,
                "nickname": "",
                "num_upgrades": 5,
                "pokemon_id": 134,
                "pokemon_name": "VAPOREON",
                "stamina": 192,
                "stamina_max": 192
            },
            {
                "VI": 86,
                "additional_cp_multiplier": 0.026084069162607193,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 1542,
                "id": 9434212886979627302,
                "individual_attack": 15,
                "individual_defense": 14,
                "individual_stamina": 14,
                "is_egg": false,
                "move_1": 204,
                "move_2": 14,
                "nickname": "",
                "num_upgrades": 3,
                "pokemon_id": 149,
                "pokemon_name": "DRAGONITE",
                "stamina": 103,
                "stamina_max": 103
            },
            {
                "VI": 86,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 124,
                "id": 17232245362946228572,
                "individual_attack": 14,
                "individual_defense": 14,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 231,
                "move_2": 133,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 129,
                "pokemon_name": "MAGIKARP",
                "stamina": 30,
                "stamina_max": 30
            },
            {
                "VI": 86,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 173,
                "id": 4275682060782384243,
                "individual_attack": 13,
                "individual_defense": 15,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 231,
                "move_2": 133,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 129,
                "pokemon_name": "MAGIKARP",
                "stamina": 35,
                "stamina_max": 35
            },
            {
                "VI": 84,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 461,
                "id": 16521268238230262501,
                "individual_attack": 14,
                "individual_defense": 15,
                "individual_stamina": 13,
                "is_egg": false,
                "move_1": 236,
                "move_2": 13,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 23,
                "pokemon_name": "EKANS",
                "stamina": 49,
                "stamina_max": 49
            },
            {
                "VI": 84,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 27,
                "id": 12532541217712350284,
                "individual_attack": 15,
                "individual_defense": 12,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 231,
                "move_2": 133,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 129,
                "pokemon_name": "MAGIKARP",
                "stamina": 14,
                "stamina_max": 14
            },
            {
                "VI": 84,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 211,
                "id": 5301710925802815422,
                "individual_attack": 13,
                "individual_defense": 14,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 211,
                "move_2": 45,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 21,
                "pokemon_name": "SPEAROW",
                "stamina": 42,
                "stamina_max": 42
            },
            {
                "VI": 84,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 382,
                "id": 1341270546720183136,
                "individual_attack": 12,
                "individual_defense": 15,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 219,
                "move_2": 38,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 21,
                "pokemon_name": "SPEAROW",
                "stamina": 56,
                "stamina_max": 56
            },
            {
                "VI": 84,
                "additional_cp_multiplier": 0.007082056254148483,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 1198,
                "id": 14212059816551142252,
                "individual_attack": 13,
                "individual_defense": 14,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 235,
                "move_2": 49,
                "nickname": "",
                "num_upgrades": 1,
                "pokemon_id": 49,
                "pokemon_name": "VENOMOTH",
                "stamina": 98,
                "stamina_max": 98
            },
            {
                "VI": 84,
                "additional_cp_multiplier": 0.08838561177253723,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 1702,
                "id": 1285885191226378086,
                "individual_attack": 15,
                "individual_defense": 15,
                "individual_stamina": 12,
                "is_egg": false,
                "move_1": 234,
                "move_2": 108,
                "nickname": "",
                "num_upgrades": 13,
                "pokemon_id": 97,
                "pokemon_name": "HYPNO",
                "stamina": 127,
                "stamina_max": 127
            },
            {
                "VI": 84,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 19,
                "id": 2590698673228409221,
                "individual_attack": 14,
                "individual_defense": 13,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 231,
                "move_2": 133,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 129,
                "pokemon_name": "MAGIKARP",
                "stamina": 11,
                "stamina_max": 11
            },
            {
                "VI": 84,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 27,
                "id": 1176269445444780859,
                "individual_attack": 14,
                "individual_defense": 13,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 219,
                "move_2": 90,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 41,
                "pokemon_name": "ZUBAT",
                "stamina": 15,
                "stamina_max": 15
            },
            {
                "VI": 84,
                "additional_cp_multiplier": 0.32530730962753296,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 2097,
                "id": 16859080494160339380,
                "individual_attack": 15,
                "individual_defense": 13,
                "individual_stamina": 14,
                "is_egg": false,
                "move_1": 202,
                "move_2": 107,
                "nickname": "",
                "num_upgrades": 39,
                "pokemon_id": 130,
                "pokemon_name": "GYARADOS",
                "stamina": 142,
                "stamina_max": 142
            },
            {
                "VI": 82,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 320,
                "id": 3370066793542430664,
                "individual_attack": 12,
                "individual_defense": 15,
                "individual_stamina": 14,
                "is_egg": false,
                "move_1": 219,
                "move_2": 26,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 19,
                "pokemon_name": "RATTATA",
                "stamina": 44,
                "stamina_max": 44
            },
            {
                "VI": 82,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 121,
                "id": 9660860926058991996,
                "individual_attack": 13,
                "individual_defense": 14,
                "individual_stamina": 14,
                "is_egg": false,
                "move_1": 231,
                "move_2": 133,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 129,
                "pokemon_name": "MAGIKARP",
                "stamina": 29,
                "stamina_max": 29
            },
            {
                "VI": 82,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 14,
                "id": 9420890147654178305,
                "individual_attack": 15,
                "individual_defense": 14,
                "individual_stamina": 12,
                "is_egg": false,
                "move_1": 222,
                "move_2": 60,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 96,
                "pokemon_name": "DROWZEE",
                "stamina": 12,
                "stamina_max": 12
            },
            {
                "VI": 82,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 238,
                "id": 3873485711152671909,
                "individual_attack": 15,
                "individual_defense": 15,
                "individual_stamina": 11,
                "is_egg": false,
                "move_1": 235,
                "move_2": 30,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 96,
                "pokemon_name": "DROWZEE",
                "stamina": 49,
                "stamina_max": 49
            },
            {
                "VI": 82,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 424,
                "id": 8047638141483855149,
                "individual_attack": 15,
                "individual_defense": 12,
                "individual_stamina": 14,
                "is_egg": false,
                "move_1": 221,
                "move_2": 131,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 133,
                "pokemon_name": "EEVEE",
                "stamina": 61,
                "stamina_max": 61
            },
            {
                "VI": 80,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 93,
                "id": 13076782310517847318,
                "individual_attack": 15,
                "individual_defense": 15,
                "individual_stamina": 10,
                "is_egg": false,
                "move_1": 231,
                "move_2": 133,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 129,
                "pokemon_name": "MAGIKARP",
                "stamina": 24,
                "stamina_max": 24
            },
            {
                "VI": 80,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 169,
                "id": 1544618485306672094,
                "individual_attack": 13,
                "individual_defense": 14,
                "individual_stamina": 13,
                "is_egg": false,
                "move_1": 231,
                "move_2": 133,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 129,
                "pokemon_name": "MAGIKARP",
                "stamina": 34,
                "stamina_max": 34
            },
            {
                "VI": 80,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 196,
                "id": 528264516849367999,
                "individual_attack": 14,
                "individual_defense": 11,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 219,
                "move_2": 90,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 41,
                "pokemon_name": "ZUBAT",
                "stamina": 42,
                "stamina_max": 42
            },
            {
                "VI": 80,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 110,
                "id": 12788098966554387548,
                "individual_attack": 15,
                "individual_defense": 14,
                "individual_stamina": 11,
                "is_egg": false,
                "move_1": 219,
                "move_2": 125,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 133,
                "pokemon_name": "EEVEE",
                "stamina": 30,
                "stamina_max": 30
            },
            {
                "VI": 80,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 127,
                "id": 18022053758639501880,
                "individual_attack": 13,
                "individual_defense": 13,
                "individual_stamina": 14,
                "is_egg": false,
                "move_1": 231,
                "move_2": 133,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 129,
                "pokemon_name": "MAGIKARP",
                "stamina": 30,
                "stamina_max": 30
            },
            {
                "VI": 80,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 283,
                "id": 17004669022328854166,
                "individual_attack": 12,
                "individual_defense": 13,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 219,
                "move_2": 80,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 21,
                "pokemon_name": "SPEAROW",
                "stamina": 49,
                "stamina_max": 49
            },
            {
                "VI": 80,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 477,
                "id": 10826805553827458285,
                "individual_attack": 13,
                "individual_defense": 15,
                "individual_stamina": 12,
                "is_egg": false,
                "move_1": 222,
                "move_2": 30,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 96,
                "pokemon_name": "DROWZEE",
                "stamina": 70,
                "stamina_max": 70
            },
            {
                "VI": 80,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 344,
                "id": 5954943764713837150,
                "individual_attack": 14,
                "individual_defense": 11,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 201,
                "move_2": 99,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 48,
                "pokemon_name": "VENONAT",
                "stamina": 62,
                "stamina_max": 62
            },
            {
                "VI": 78,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 732,
                "id": 6305446346094349582,
                "individual_attack": 14,
                "individual_defense": 10,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 239,
                "move_2": 46,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 22,
                "pokemon_name": "FEAROW",
                "stamina": 75,
                "stamina_max": 75
            },
            {
                "VI": 78,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 148,
                "id": 706814031344891325,
                "individual_attack": 14,
                "individual_defense": 14,
                "individual_stamina": 11,
                "is_egg": false,
                "move_1": 231,
                "move_2": 133,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 129,
                "pokemon_name": "MAGIKARP",
                "stamina": 31,
                "stamina_max": 31
            },
            {
                "VI": 78,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 376,
                "id": 4736651550111101805,
                "individual_attack": 14,
                "individual_defense": 12,
                "individual_stamina": 13,
                "is_egg": false,
                "move_1": 203,
                "move_2": 16,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 92,
                "pokemon_name": "GASTLY",
                "stamina": 40,
                "stamina_max": 40
            },
            {
                "VI": 78,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 666,
                "id": 4213250659983219447,
                "individual_attack": 13,
                "individual_defense": 13,
                "individual_stamina": 13,
                "is_egg": false,
                "move_1": 234,
                "move_2": 87,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 35,
                "pokemon_name": "CLEFAIRY",
                "stamina": 91,
                "stamina_max": 91
            },
            {
                "VI": 78,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 91,
                "id": 2600559741645438724,
                "individual_attack": 13,
                "individual_defense": 13,
                "individual_stamina": 13,
                "is_egg": false,
                "move_1": 231,
                "move_2": 133,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 129,
                "pokemon_name": "MAGIKARP",
                "stamina": 25,
                "stamina_max": 25
            },
            {
                "VI": 78,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 511,
                "id": 14825245838577102847,
                "individual_attack": 15,
                "individual_defense": 13,
                "individual_stamina": 11,
                "is_egg": false,
                "move_1": 235,
                "move_2": 108,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 96,
                "pokemon_name": "DROWZEE",
                "stamina": 72,
                "stamina_max": 72
            },
            {
                "VI": 76,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 607,
                "id": 12807680985375289417,
                "individual_attack": 14,
                "individual_defense": 11,
                "individual_stamina": 13,
                "is_egg": false,
                "move_1": 220,
                "move_2": 59,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 46,
                "pokemon_name": "PARAS",
                "stamina": 54,
                "stamina_max": 54
            },
            {
                "VI": 76,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 675,
                "id": 17466784695533750975,
                "individual_attack": 15,
                "individual_defense": 14,
                "individual_stamina": 9,
                "is_egg": false,
                "move_1": 202,
                "move_2": 80,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 130,
                "pokemon_name": "GYARADOS",
                "stamina": 79,
                "stamina_max": 79
            },
            {
                "VI": 76,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 25,
                "id": 11307411211398087260,
                "individual_attack": 13,
                "individual_defense": 10,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 231,
                "move_2": 133,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 129,
                "pokemon_name": "MAGIKARP",
                "stamina": 14,
                "stamina_max": 14
            },
            {
                "VI": 76,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 601,
                "id": 16245227624706985374,
                "individual_attack": 11,
                "individual_defense": 13,
                "individual_stamina": 14,
                "is_egg": false,
                "move_1": 235,
                "move_2": 62,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 102,
                "pokemon_name": "EXEGGCUTE",
                "stamina": 80,
                "stamina_max": 80
            },
            {
                "VI": 76,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 472,
                "id": 2241360834999555121,
                "individual_attack": 8,
                "individual_defense": 15,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 221,
                "move_2": 45,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 16,
                "pokemon_name": "PIDGEY",
                "stamina": 64,
                "stamina_max": 64
            },
            {
                "VI": 76,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 248,
                "id": 11031310257071150822,
                "individual_attack": 14,
                "individual_defense": 10,
                "individual_stamina": 14,
                "is_egg": false,
                "move_1": 216,
                "move_2": 96,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 50,
                "pokemon_name": "DIGLETT",
                "stamina": 20,
                "stamina_max": 20
            },
            {
                "VI": 76,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 174,
                "id": 3496307358201341525,
                "individual_attack": 14,
                "individual_defense": 15,
                "individual_stamina": 9,
                "is_egg": false,
                "move_1": 231,
                "move_2": 133,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 129,
                "pokemon_name": "MAGIKARP",
                "stamina": 32,
                "stamina_max": 32
            },
            {
                "VI": 76,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 186,
                "id": 7447889941947139206,
                "individual_attack": 14,
                "individual_defense": 10,
                "individual_stamina": 14,
                "is_egg": false,
                "move_1": 220,
                "move_2": 16,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 52,
                "pokemon_name": "MEOWTH",
                "stamina": 37,
                "stamina_max": 37
            },
            {
                "VI": 74,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 210,
                "id": 418480589126015058,
                "individual_attack": 15,
                "individual_defense": 12,
                "individual_stamina": 10,
                "is_egg": false,
                "move_1": 217,
                "move_2": 111,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 86,
                "pokemon_name": "SEEL",
                "stamina": 48,
                "stamina_max": 48
            },
            {
                "VI": 74,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 10,
                "id": 5812061365484304374,
                "individual_attack": 15,
                "individual_defense": 7,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 231,
                "move_2": 133,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 129,
                "pokemon_name": "MAGIKARP",
                "stamina": 10,
                "stamina_max": 10
            },
            {
                "VI": 74,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 93,
                "id": 7430974139956735870,
                "individual_attack": 14,
                "individual_defense": 14,
                "individual_stamina": 9,
                "is_egg": false,
                "move_1": 238,
                "move_2": 84,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 39,
                "pokemon_name": "JIGGLYPUFF",
                "stamina": 61,
                "stamina_max": 61
            },
            {
                "VI": 74,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 399,
                "id": 15860815723799001516,
                "individual_attack": 15,
                "individual_defense": 7,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 220,
                "move_2": 62,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 140,
                "pokemon_name": "KABUTO",
                "stamina": 36,
                "stamina_max": 36
            },
            {
                "VI": 74,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 329,
                "id": 3531130124290632067,
                "individual_attack": 9,
                "individual_defense": 15,
                "individual_stamina": 13,
                "is_egg": false,
                "move_1": 202,
                "move_2": 131,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 29,
                "pokemon_name": "NIDORAN_FEMALE",
                "stamina": 61,
                "stamina_max": 61
            },
            {
                "VI": 74,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 115,
                "id": 7798231909348007364,
                "individual_attack": 13,
                "individual_defense": 10,
                "individual_stamina": 14,
                "is_egg": false,
                "move_1": 205,
                "move_2": 79,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 81,
                "pokemon_name": "MAGNEMITE",
                "stamina": 18,
                "stamina_max": 18
            },
            {
                "VI": 74,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 63,
                "id": 14129253408142171212,
                "individual_attack": 14,
                "individual_defense": 9,
                "individual_stamina": 14,
                "is_egg": false,
                "move_1": 231,
                "move_2": 133,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 129,
                "pokemon_name": "MAGIKARP",
                "stamina": 21,
                "stamina_max": 21
            },
            {
                "VI": 74,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 267,
                "id": 7156877450280955485,
                "individual_attack": 15,
                "individual_defense": 9,
                "individual_stamina": 13,
                "is_egg": false,
                "move_1": 235,
                "move_2": 108,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 96,
                "pokemon_name": "DROWZEE",
                "stamina": 53,
                "stamina_max": 53
            },
            {
                "VI": 74,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 832,
                "id": 292940782906375093,
                "individual_attack": 11,
                "individual_defense": 15,
                "individual_stamina": 11,
                "is_egg": false,
                "move_1": 221,
                "move_2": 21,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 77,
                "pokemon_name": "PONYTA",
                "stamina": 66,
                "stamina_max": 66
            },
            {
                "VI": 72,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 537,
                "id": 1526250326048343078,
                "individual_attack": 14,
                "individual_defense": 11,
                "individual_stamina": 11,
                "is_egg": false,
                "move_1": 235,
                "move_2": 50,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 48,
                "pokemon_name": "VENONAT",
                "stamina": 76,
                "stamina_max": 76
            },
            {
                "VI": 72,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 775,
                "id": 16513123280517183622,
                "individual_attack": 6,
                "individual_defense": 15,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 235,
                "move_2": 108,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 79,
                "pokemon_name": "SLOWPOKE",
                "stamina": 127,
                "stamina_max": 127
            },
            {
                "VI": 72,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 472,
                "id": 3206589845061534004,
                "individual_attack": 15,
                "individual_defense": 10,
                "individual_stamina": 11,
                "is_egg": false,
                "move_1": 227,
                "move_2": 32,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 95,
                "pokemon_name": "ONIX",
                "stamina": 48,
                "stamina_max": 48
            },
            {
                "VI": 72,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 370,
                "id": 14223972142197540011,
                "individual_attack": 15,
                "individual_defense": 6,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 237,
                "move_2": 53,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 98,
                "pokemon_name": "KRABBY",
                "stamina": 41,
                "stamina_max": 41
            },
            {
                "VI": 72,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 415,
                "id": 11855560623933843225,
                "individual_attack": 15,
                "individual_defense": 10,
                "individual_stamina": 11,
                "is_egg": false,
                "move_1": 211,
                "move_2": 131,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 32,
                "pokemon_name": "NIDORAN_MALE",
                "stamina": 58,
                "stamina_max": 58
            },
            {
                "VI": 70,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 450,
                "id": 15657867101611564037,
                "individual_attack": 13,
                "individual_defense": 10,
                "individual_stamina": 12,
                "is_egg": false,
                "move_1": 209,
                "move_2": 131,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 37,
                "pokemon_name": "VULPIX",
                "stamina": 52,
                "stamina_max": 52
            },
            {
                "VI": 70,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 681,
                "id": 12091102368325391847,
                "individual_attack": 15,
                "individual_defense": 11,
                "individual_stamina": 9,
                "is_egg": false,
                "move_1": 235,
                "move_2": 30,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 96,
                "pokemon_name": "DROWZEE",
                "stamina": 82,
                "stamina_max": 82
            },
            {
                "VI": 70,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 426,
                "id": 15415659330340811925,
                "individual_attack": 10,
                "individual_defense": 11,
                "individual_stamina": 14,
                "is_egg": false,
                "move_1": 216,
                "move_2": 63,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 27,
                "pokemon_name": "SANDSHREW",
                "stamina": 68,
                "stamina_max": 68
            },
            {
                "VI": 68,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 105,
                "id": 14120850592885161150,
                "individual_attack": 15,
                "individual_defense": 5,
                "individual_stamina": 14,
                "is_egg": false,
                "move_1": 231,
                "move_2": 133,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 129,
                "pokemon_name": "MAGIKARP",
                "stamina": 27,
                "stamina_max": 27
            },
            {
                "VI": 68,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 814,
                "id": 4394890725843772153,
                "individual_attack": 4,
                "individual_defense": 15,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 216,
                "move_2": 96,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 61,
                "pokemon_name": "POLIWHIRL",
                "stamina": 92,
                "stamina_max": 92
            },
            {
                "VI": 68,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 564,
                "id": 10899750895291099219,
                "individual_attack": 15,
                "individual_defense": 10,
                "individual_stamina": 9,
                "is_egg": false,
                "move_1": 221,
                "move_2": 16,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 109,
                "pokemon_name": "KOFFING",
                "stamina": 50,
                "stamina_max": 50
            },
            {
                "VI": 68,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 448,
                "id": 6658213675527698294,
                "individual_attack": 14,
                "individual_defense": 7,
                "individual_stamina": 13,
                "is_egg": false,
                "move_1": 220,
                "move_2": 131,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 52,
                "pokemon_name": "MEOWTH",
                "stamina": 58,
                "stamina_max": 58
            },
            {
                "VI": 68,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 28,
                "id": 2395586650431394880,
                "individual_attack": 14,
                "individual_defense": 10,
                "individual_stamina": 10,
                "is_egg": false,
                "move_1": 239,
                "move_2": 100,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 123,
                "pokemon_name": "SCYTHER",
                "stamina": 14,
                "stamina_max": 14
            },
            {
                "VI": 68,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 669,
                "id": 9718651703710191935,
                "individual_attack": 10,
                "individual_defense": 10,
                "individual_stamina": 14,
                "is_egg": false,
                "move_1": 205,
                "move_2": 35,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 82,
                "pokemon_name": "MAGNETON",
                "stamina": 54,
                "stamina_max": 54
            },
            {
                "VI": 66,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 400,
                "id": 11177237172385481271,
                "individual_attack": 15,
                "individual_defense": 15,
                "individual_stamina": 3,
                "is_egg": false,
                "move_1": 212,
                "move_2": 90,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 92,
                "pokemon_name": "GASTLY",
                "stamina": 36,
                "stamina_max": 36
            },
            {
                "VI": 66,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 371,
                "id": 9767826171569838115,
                "individual_attack": 15,
                "individual_defense": 3,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 230,
                "move_2": 40,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 117,
                "pokemon_name": "SEADRA",
                "stamina": 46,
                "stamina_max": 46
            },
            {
                "VI": 66,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 474,
                "id": 4628363833850743319,
                "individual_attack": 4,
                "individual_defense": 14,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 237,
                "move_2": 96,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 60,
                "pokemon_name": "POLIWAG",
                "stamina": 60,
                "stamina_max": 60
            },
            {
                "VI": 64,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 587,
                "id": 10184504196613048729,
                "individual_attack": 5,
                "individual_defense": 12,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 237,
                "move_2": 105,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 72,
                "pokemon_name": "TENTACOOL",
                "stamina": 63,
                "stamina_max": 63
            },
            {
                "VI": 62,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 1309,
                "id": 1105874762571812893,
                "individual_attack": 11,
                "individual_defense": 7,
                "individual_stamina": 13,
                "is_egg": false,
                "move_1": 219,
                "move_2": 30,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 121,
                "pokemon_name": "STARMIE",
                "stamina": 83,
                "stamina_max": 83
            },
            {
                "VI": 62,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 636,
                "id": 15067841907185512539,
                "individual_attack": 10,
                "individual_defense": 13,
                "individual_stamina": 8,
                "is_egg": false,
                "move_1": 219,
                "move_2": 125,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 120,
                "pokemon_name": "STARYU",
                "stamina": 46,
                "stamina_max": 46
            },
            {
                "VI": 62,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 528,
                "id": 8218358193809739004,
                "individual_attack": 15,
                "individual_defense": 14,
                "individual_stamina": 2,
                "is_egg": false,
                "move_1": 216,
                "move_2": 104,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 138,
                "pokemon_name": "OMANYTE",
                "stamina": 40,
                "stamina_max": 40
            },
            {
                "VI": 62,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 972,
                "id": 10676654463957961576,
                "individual_attack": 13,
                "individual_defense": 12,
                "individual_stamina": 6,
                "is_egg": false,
                "move_1": 219,
                "move_2": 26,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 20,
                "pokemon_name": "RATICATE",
                "stamina": 77,
                "stamina_max": 77
            },
            {
                "VI": 62,
                "additional_cp_multiplier": 0.007423647679388523,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 1784,
                "id": 12211759490574569966,
                "individual_attack": 15,
                "individual_defense": 15,
                "individual_stamina": 1,
                "is_egg": false,
                "move_1": 212,
                "move_2": 31,
                "nickname": "",
                "num_upgrades": 1,
                "pokemon_id": 143,
                "pokemon_name": "SNORLAX",
                "stamina": 194,
                "stamina_max": 194
            },
            {
                "VI": 62,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 629,
                "id": 3862495022488847078,
                "individual_attack": 6,
                "individual_defense": 10,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 216,
                "move_2": 126,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 118,
                "pokemon_name": "GOLDEEN",
                "stamina": 70,
                "stamina_max": 70
            },
            {
                "VI": 62,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 397,
                "id": 16600393597772805581,
                "individual_attack": 15,
                "individual_defense": 3,
                "individual_stamina": 13,
                "is_egg": false,
                "move_1": 221,
                "move_2": 111,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 90,
                "pokemon_name": "SHELLDER",
                "stamina": 41,
                "stamina_max": 41
            },
            {
                "VI": 60,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 647,
                "id": 15208219987620805716,
                "individual_attack": 14,
                "individual_defense": 14,
                "individual_stamina": 2,
                "is_egg": false,
                "move_1": 208,
                "move_2": 56,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 66,
                "pokemon_name": "MACHOP",
                "stamina": 88,
                "stamina_max": 88
            },
            {
                "VI": 60,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 712,
                "id": 6177399648993192006,
                "individual_attack": 9,
                "individual_defense": 12,
                "individual_stamina": 9,
                "is_egg": false,
                "move_1": 239,
                "move_2": 80,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 17,
                "pokemon_name": "PIDGEOTTO",
                "stamina": 84,
                "stamina_max": 84
            },
            {
                "VI": 60,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 393,
                "id": 3051736919397688817,
                "individual_attack": 12,
                "individual_defense": 4,
                "individual_stamina": 14,
                "is_egg": false,
                "move_1": 219,
                "move_2": 26,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 19,
                "pokemon_name": "RATTATA",
                "stamina": 50,
                "stamina_max": 50
            },
            {
                "VI": 60,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 440,
                "id": 4748741480272203776,
                "individual_attack": 14,
                "individual_defense": 4,
                "individual_stamina": 12,
                "is_egg": false,
                "move_1": 202,
                "move_2": 50,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 41,
                "pokemon_name": "ZUBAT",
                "stamina": 62,
                "stamina_max": 62
            },
            {
                "VI": 58,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 451,
                "id": 8841697978059794306,
                "individual_attack": 8,
                "individual_defense": 14,
                "individual_stamina": 7,
                "is_egg": false,
                "move_1": 206,
                "move_2": 72,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 81,
                "pokemon_name": "MAGNEMITE",
                "stamina": 34,
                "stamina_max": 34
            },
            {
                "VI": 58,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 486,
                "id": 2772441342288607272,
                "individual_attack": 14,
                "individual_defense": 1,
                "individual_stamina": 14,
                "is_egg": false,
                "move_1": 220,
                "move_2": 123,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 56,
                "pokemon_name": "MANKEY",
                "stamina": 57,
                "stamina_max": 57
            },
            {
                "VI": 58,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 591,
                "id": 7060364732025366703,
                "individual_attack": 15,
                "individual_defense": 10,
                "individual_stamina": 4,
                "is_egg": false,
                "move_1": 233,
                "move_2": 18,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 88,
                "pokemon_name": "GRIMER",
                "stamina": 90,
                "stamina_max": 90
            },
            {
                "VI": 58,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 582,
                "id": 12132100363842075907,
                "individual_attack": 13,
                "individual_defense": 4,
                "individual_stamina": 12,
                "is_egg": false,
                "move_1": 215,
                "move_2": 59,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 43,
                "pokemon_name": "ODDISH",
                "stamina": 59,
                "stamina_max": 59
            },
            {
                "VI": 54,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 264,
                "id": 14001614070928803235,
                "individual_attack": 14,
                "individual_defense": 8,
                "individual_stamina": 5,
                "is_egg": false,
                "move_1": 235,
                "move_2": 86,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 64,
                "pokemon_name": "KADABRA",
                "stamina": 33,
                "stamina_max": 33
            },
            {
                "VI": 54,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 350,
                "id": 7930876174652463189,
                "individual_attack": 15,
                "individual_defense": 4,
                "individual_stamina": 8,
                "is_egg": false,
                "move_1": 206,
                "move_2": 79,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 101,
                "pokemon_name": "ELECTRODE",
                "stamina": 48,
                "stamina_max": 48
            },
            {
                "VI": 54,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 334,
                "id": 12942355209307534306,
                "individual_attack": 4,
                "individual_defense": 15,
                "individual_stamina": 8,
                "is_egg": false,
                "move_1": 201,
                "move_2": 45,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 15,
                "pokemon_name": "BEEDRILL",
                "stamina": 55,
                "stamina_max": 55
            },
            {
                "VI": 54,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 970,
                "id": 16448199582001940140,
                "individual_attack": 6,
                "individual_defense": 14,
                "individual_stamina": 7,
                "is_egg": false,
                "move_1": 230,
                "move_2": 39,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 80,
                "pokemon_name": "SLOWBRO",
                "stamina": 98,
                "stamina_max": 98
            },
            {
                "VI": 52,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 527,
                "id": 16581481040467290716,
                "individual_attack": 15,
                "individual_defense": 5,
                "individual_stamina": 6,
                "is_egg": false,
                "move_1": 221,
                "move_2": 99,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 100,
                "pokemon_name": "VOLTORB",
                "stamina": 56,
                "stamina_max": 56
            },
            {
                "VI": 52,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 964,
                "id": 2121754525071841675,
                "individual_attack": 14,
                "individual_defense": 3,
                "individual_stamina": 9,
                "is_egg": false,
                "move_1": 201,
                "move_2": 50,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 49,
                "pokemon_name": "VENOMOTH",
                "stamina": 86,
                "stamina_max": 86
            },
            {
                "VI": 52,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 501,
                "id": 11426477567821159189,
                "individual_attack": 0,
                "individual_defense": 11,
                "individual_stamina": 15,
                "is_egg": false,
                "move_1": 221,
                "move_2": 105,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 7,
                "pokemon_name": "SQUIRTLE",
                "stamina": 61,
                "stamina_max": 61
            },
            {
                "VI": 52,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 522,
                "id": 7940229703415736517,
                "individual_attack": 4,
                "individual_defense": 12,
                "individual_stamina": 10,
                "is_egg": false,
                "move_1": 216,
                "move_2": 107,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 62,
                "pokemon_name": "POLIWRATH",
                "stamina": 71,
                "stamina_max": 71
            },
            {
                "VI": 52,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 1384,
                "id": 11217723921587409309,
                "individual_attack": 2,
                "individual_defense": 10,
                "individual_stamina": 14,
                "is_egg": false,
                "move_1": 230,
                "move_2": 107,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 55,
                "pokemon_name": "GOLDUCK",
                "stamina": 109,
                "stamina_max": 109
            },
            {
                "VI": 50,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 512,
                "id": 4743926328027359065,
                "individual_attack": 14,
                "individual_defense": 3,
                "individual_stamina": 8,
                "is_egg": false,
                "move_1": 238,
                "move_2": 88,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 39,
                "pokemon_name": "JIGGLYPUFF",
                "stamina": 149,
                "stamina_max": 149
            },
            {
                "VI": 48,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 298,
                "id": 11351355101669306181,
                "individual_attack": 3,
                "individual_defense": 11,
                "individual_stamina": 10,
                "is_egg": false,
                "move_1": 219,
                "move_2": 45,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 84,
                "pokemon_name": "DODUO",
                "stamina": 39,
                "stamina_max": 39
            },
            {
                "VI": 48,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 972,
                "id": 9031224677292484871,
                "individual_attack": 14,
                "individual_defense": 8,
                "individual_stamina": 2,
                "is_egg": false,
                "move_1": 211,
                "move_2": 46,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 22,
                "pokemon_name": "FEAROW",
                "stamina": 80,
                "stamina_max": 80
            },
            {
                "VI": 46,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 309,
                "id": 6307743639514764567,
                "individual_attack": 2,
                "individual_defense": 10,
                "individual_stamina": 11,
                "is_egg": false,
                "move_1": 209,
                "move_2": 24,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 4,
                "pokemon_name": "CHARMANDER",
                "stamina": 42,
                "stamina_max": 42
            },
            {
                "VI": 46,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 394,
                "id": 16770611724911347958,
                "individual_attack": 15,
                "individual_defense": 7,
                "individual_stamina": 1,
                "is_egg": false,
                "move_1": 237,
                "move_2": 20,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 98,
                "pokemon_name": "KRABBY",
                "stamina": 36,
                "stamina_max": 36
            },
            {
                "VI": 44,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 517,
                "id": 17935795421512119148,
                "individual_attack": 15,
                "individual_defense": 2,
                "individual_stamina": 5,
                "is_egg": false,
                "move_1": 230,
                "move_2": 53,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 116,
                "pokemon_name": "HORSEA",
                "stamina": 44,
                "stamina_max": 44
            },
            {
                "VI": 44,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 445,
                "id": 16848583715712583781,
                "individual_attack": 13,
                "individual_defense": 6,
                "individual_stamina": 3,
                "is_egg": false,
                "move_1": 211,
                "move_2": 38,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 21,
                "pokemon_name": "SPEAROW",
                "stamina": 56,
                "stamina_max": 56
            },
            {
                "VI": 44,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 454,
                "id": 14081300368749762260,
                "individual_attack": 2,
                "individual_defense": 7,
                "individual_stamina": 13,
                "is_egg": false,
                "move_1": 221,
                "move_2": 118,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 1,
                "pokemon_name": "BULBASAUR",
                "stamina": 56,
                "stamina_max": 56
            },
            {
                "VI": 42,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 576,
                "id": 4698873514178031835,
                "individual_attack": 4,
                "individual_defense": 11,
                "individual_stamina": 6,
                "is_egg": false,
                "move_1": 217,
                "move_2": 57,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 86,
                "pokemon_name": "SEEL",
                "stamina": 83,
                "stamina_max": 83
            },
            {
                "VI": 42,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 243,
                "id": 14926447812271817685,
                "individual_attack": 4,
                "individual_defense": 4,
                "individual_stamina": 13,
                "is_egg": false,
                "move_1": 201,
                "move_2": 133,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 14,
                "pokemon_name": "KAKUNA",
                "stamina": 64,
                "stamina_max": 64
            },
            {
                "VI": 42,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 229,
                "id": 3939131154403518657,
                "individual_attack": 14,
                "individual_defense": 5,
                "individual_stamina": 2,
                "is_egg": false,
                "move_1": 234,
                "move_2": 60,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 63,
                "pokemon_name": "ABRA",
                "stamina": 27,
                "stamina_max": 27
            },
            {
                "VI": 42,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 733,
                "id": 11377780889227616453,
                "individual_attack": 3,
                "individual_defense": 10,
                "individual_stamina": 8,
                "is_egg": false,
                "move_1": 241,
                "move_2": 127,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 111,
                "pokemon_name": "RHYHORN",
                "stamina": 112,
                "stamina_max": 112
            },
            {
                "VI": 40,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 669,
                "id": 1378804528905105882,
                "individual_attack": 13,
                "individual_defense": 0,
                "individual_stamina": 7,
                "is_egg": false,
                "move_1": 225,
                "move_2": 118,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 69,
                "pokemon_name": "BELLSPROUT",
                "stamina": 70,
                "stamina_max": 70
            },
            {
                "VI": 38,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 708,
                "id": 421438039546575939,
                "individual_attack": 1,
                "individual_defense": 8,
                "individual_stamina": 10,
                "is_egg": false,
                "move_1": 234,
                "move_2": 30,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 54,
                "pokemon_name": "PSYDUCK",
                "stamina": 74,
                "stamina_max": 74
            },
            {
                "VI": 36,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 261,
                "id": 10699464638721377071,
                "individual_attack": 3,
                "individual_defense": 10,
                "individual_stamina": 5,
                "is_egg": false,
                "move_1": 236,
                "move_2": 133,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 13,
                "pokemon_name": "WEEDLE",
                "stamina": 57,
                "stamina_max": 57
            },
            {
                "VI": 34,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 1204,
                "id": 17452867304606735211,
                "individual_attack": 5,
                "individual_defense": 0,
                "individual_stamina": 12,
                "is_egg": false,
                "move_1": 224,
                "move_2": 91,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 73,
                "pokemon_name": "TENTACRUEL",
                "stamina": 105,
                "stamina_max": 105
            },
            {
                "VI": 34,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 1100,
                "id": 12700407916733725774,
                "individual_attack": 2,
                "individual_defense": 13,
                "individual_stamina": 2,
                "is_egg": false,
                "move_1": 209,
                "move_2": 103,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 126,
                "pokemon_name": "MAGMAR",
                "stamina": 76,
                "stamina_max": 76
            },
            {
                "VI": 32,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 361,
                "id": 124685054842621347,
                "individual_attack": 1,
                "individual_defense": 5,
                "individual_stamina": 10,
                "is_egg": false,
                "move_1": 221,
                "move_2": 64,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 74,
                "pokemon_name": "GEODUDE",
                "stamina": 51,
                "stamina_max": 51
            },
            {
                "VI": 28,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 798,
                "id": 13153702110968544667,
                "individual_attack": 5,
                "individual_defense": 7,
                "individual_stamina": 2,
                "is_egg": false,
                "move_1": 239,
                "move_2": 122,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 18,
                "pokemon_name": "PIDGEOT",
                "stamina": 86,
                "stamina_max": 86
            },
            {
                "VI": 24,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 10,
                "id": 16930121912856548868,
                "individual_attack": 0,
                "individual_defense": 10,
                "individual_stamina": 2,
                "is_egg": false,
                "move_1": 201,
                "move_2": 133,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 11,
                "pokemon_name": "METAPOD",
                "stamina": 10,
                "stamina_max": 10
            },
            {
                "VI": 24,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 250,
                "id": 18139539731788068897,
                "individual_attack": 1,
                "individual_defense": 6,
                "individual_stamina": 5,
                "is_egg": false,
                "move_1": 200,
                "move_2": 100,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 127,
                "pokemon_name": "PINSIR",
                "stamina": 39,
                "stamina_max": 39
            },
            {
                "VI": 20,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 218,
                "id": 14813396737945316254,
                "individual_attack": 0,
                "individual_defense": 6,
                "individual_stamina": 4,
                "is_egg": false,
                "move_1": 201,
                "move_2": 133,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 10,
                "pokemon_name": "CATERPIE",
                "stamina": 61,
                "stamina_max": 61
            },
            {
                "VI": 12,
                "additional_cp_multiplier": 0.0,
                "battles_attacked": 0,
                "battles_defended": 0,
                "cp": 108,
                "id": 10237391435921282131,
                "individual_attack": 0,
                "individual_defense": 1,
                "individual_stamina": 5,
                "is_egg": false,
                "move_1": 233,
                "move_2": 95,
                "nickname": "",
                "num_upgrades": 0,
                "pokemon_id": 104,
                "pokemon_name": "CUBONE",
                "stamina": 30,
                "stamina_max": 30
            }
        ]
    }]);